@echo off

md "Lorem"
md "i.psum"
md "dolor"
md "sit"
md "amet"
md "con. sectetur"
md "adipiscing"
md "elit"
md "Duis"
md "tinci dunt"
md "odio"
md "sit"
md "amet"
md "feugiat"
md "aliq uet"
md "ex"
md "tortor"
md "ferme(ntu)m"
md "leo"
md "id"
md "euismod"
md "sem"
md "l ect us"
md "et"
md "odio"
md "Int_eger"
md "vitae"
md "urna"
md "p.lacerat"
md "consectetur"
md "s(apien)"
md "id"
md "feugiat"
md "felis"
md "Nulla"
md "elementum"
md "sem"
md "e get"
md "lacinia"
md "gravida"
md "Sed"
md "h_endrerit"
md "interdum"
md "eros"
md "id"
md "maximus"
md "est"
md "v,est,ibulum"
md "et"
md "Proin"
md "et"
md "blandit"
md "mi"
md "Nulla"
md "facilisi"
md "Suspendisse"
md "eu"
md "p h aretra"
md "erat"
md "A-liquam"
md "vulputate"
md "feugiat"
md "elit"
md "id"
md "aliquam"
md "ipsum"
md "varius"
md "sed"
md "Orci"
md "varius"
md "natoque"
md "penatibus"
md "et"
md "magnis"
md "dis"
md "parturient"
md "montes"
md "nascetur"
md "ridiculus"
md "mus"
md "Nulla"
md "tincidunt"
md "tristique"
md "sapien"
md "id"
md "iaculis"
md "orci"
md "interdum"
md "vel"
md "Vestibulum"
md "eget"
md "eros"
md "lorem"
md "In teger"
md "facilisis"
md "p_retium"
md "ipsum"
md "ma.ximus"
md "lobortis"
md "est"

type nul > "tempus.txt"
type nul > "eu.txt"
type nul > "Quisque.txt"
type nul > "egestas.txt"
type nul > "ut.txt"
type nul > "ex.txt"
type nul > "id.txt"
type nul > "egestas.txt"
type nul > "Cras.txt"
type nul > "libero.txt"
type nul > "felis.txt"
type nul > "fringilla.txt"
type nul > "q.uis.txt"
type nul > "tellus.txt"
type nul > "vel.txt"
type nul > "ultricies.txt"
type nul > "tempor.txt"
type nul > "i psum.txt"
type nul > "Etiam.txt"
type nul > "non.txt"
type nul > "varius.txt"
type nul > "nulla.txt"
type nul > "Integer.txt"
type nul > "laoreet.txt"
type nul > "ipsum.txt"
type nul > "_elementum.txt"
type nul > "viverra.txt"
type nul > "convallis.txt"
type nul > "sapien.txt"
type nul > "an te.txt"
type nul > "h endre rit.txt"
type nul > "lorem.txt"
type nul > "at.txt"
type nul > "c_ursus.txt"
type nul > "velit.txt"
type nul > "dolor.txt"
type nul > "in.txt"
type nul > "metus.txt"
type nul > "Praesent.txt"
type nul > "m(a)uris.txt"
type nul > "metus.txt"
type nul > "tempus.txt"
type nul > "nec.txt"
type nul > "est.txt"
type nul > "o_r_nare.txt"
type nul > "pulvinar.txt"
type nul > "gravida.txt"
type nul > "m.a.s.s.a.txt"
type nul > "Praesent.txt"
type nul > "posuere.txt"
type nul > "purus.txt"
type nul > "sed.txt"
type nul > "justo.txt"
type nul > "malesuada.txt"
type nul > "nec.txt"
type nul > "porta.txt"
type nul > "m assa.txt"
type nul > "sagittis.txt"
type nul > "Vivamus.txt"
type nul > "gravida.txt"
type nul > "m o l l i s.txt"
type nul > "sem.txt"
type nul > "ut.txt"
type nul > "rhoncus.txt"
type nul > "tellus.txt"
type nul > "Integer.txt"
type nul > "vehicula.txt"
type nul > "b__ibendum.txt"
type nul > "dui.txt"
type nul > "so dales.txt"
type nul > "elementum.txt"
type nul > "Nullam.txt"
type nul > "sed.txt"
type nul > "m_a_uris.txt"
type nul > "a.txt"
type nul > "odio.txt"
type nul > "d(i)ctum.txt"
type nul > "finibus.txt"
type nul > "ac.txt"
type nul > "et.txt"
type nul > "risus.txt"
type nul > "Nunc.txt"
type nul > "ut.txt"
type nul > "arcu.txt"
type nul > "ac.txt"
type nul > "nisi.txt"
type nul > "varius.txt"
type nul > "imperdiet.txt"
type nul > "non.txt"
type nul > "ac.txt"
type nul > "urna.txt"
type nul > "Vestibulum.txt"
type nul > "tincidunt.txt"
type nul > "arcu.txt"
type nul > "ut.txt"
type nul > "porttitor.txt"
type nul > "eleifend.txt"
type nul > "Mauris.txt"
type nul > "sit.txt"
type nul > "amet.txt"
type nul > "d apibus.txt"
type nul > "lacus.txt"
type nul > "S-uspendisse.txt"
type nul > "potenti.txt"
type nul > "V i-vamus.txt"
type nul > "vel.txt"
type nul > "metus.txt"
type nul > "vel.txt"
type nul > "e-r-os.txt"
type nul > "finibus.txt"
type nul > "rutrum.txt"
type nul > "ut.txt"
type nul > "nec.txt"
type nul > "lacus.txt"
type nul > "Donec.txt"
type nul > "ut.txt"
type nul > "turpis.txt"
type nul > "dictum.txt"
type nul > "dapibus.txt"
type nul > "nisl.txt"
type nul > "eget.txt"
type nul > "imperdiet.txt"
type nul > "nunc.txt"
type nul > "Sed.txt"
type nul > "elementum.txt"
type nul > "nibh.txt"
type nul > "sed.txt"
type nul > "nisi.txt"
type nul > "suscipit.txt"
type nul > "vulputate.txt"
type nul > "Vivamus.txt"
type nul > "volutpat.txt"
type nul > "ultrices.txt"
type nul > "sapien.txt"
type nul > "nec.txt"
type nul > "consectetur.txt"
type nul > "Sed.txt"
type nul > "rhoncus.txt"
type nul > "nisi.txt"
type nul > "a.txt"
type nul > "massa.txt"
type nul > "semper.txt"
type nul > "sollicitudin.txt"
type nul > "Sed.txt"
type nul > "placerat.txt"
type nul > "maximus.txt"
type nul > "vulputate.txt"
type nul > "Lorem.txt"
type nul > "ipsum.txt"
type nul > "dolor.txt"
type nul > "sit.txt"
type nul > "amet.txt"
type nul > "consectetur.txt"
type nul > "adipiscing.txt"
type nul > "elit.txt"
type nul > "Donec.txt"
type nul > "eleifend.txt"
type nul > "vel.txt"
type nul > "arcu.txt"
type nul > "et.txt"
type nul > "placerat.txt"
type nul > "Proin.txt"
type nul > "ac.txt"
type nul > "nisl.txt"
type nul > "a.txt"
type nul > "ipsum.txt"
type nul > "ultrices.txt"
type nul > "hendrerit.txt"
type nul > "Mauris.txt"
type nul > "vitae.txt"
type nul > "molestie.txt"
type nul > "ipsum.txt"
type nul > "condimentum.txt"
type nul > "pharetra.txt"
type nul > "orci.txt"
type nul > "Donec.txt"
type nul > "eu.txt"
type nul > "sem.txt"
type nul > "id.txt"
type nul > "risus.txt"
type nul > "tempus.txt"
type nul > "consequat.txt"
type nul > "vel.txt"
type nul > "vitae.txt"
type nul > "tellus.txt"
type nul > "Nunc.txt"
type nul > "lacinia.txt"
type nul > "leo.txt"
type nul > "quis.txt"
type nul > "tellus.txt"
type nul > "ultricies.txt"
type nul > "auctor.txt"
type nul > "Aliquam.txt"
type nul > "auctor.txt"
type nul > "gravida.txt"
type nul > "quam.txt"
type nul > "non.txt"
type nul > "imperdiet.txt"
type nul > "Nam.txt"
type nul > "commodo.txt"
type nul > "fringilla.txt"
type nul > "ante.txt"
type nul > "sit.txt"
type nul > "amet.txt"
type nul > "fermentum.txt"
type nul > "nibh.txt"
type nul > "viverra.txt"
type nul > "ut.txt"
type nul > "In.txt"
type nul > "porta.txt"
type nul > "fermentum.txt"
type nul > "semper.txt"
type nul > "Donec.txt"
type nul > "vitae.txt"
type nul > "dui.txt"
type nul > "bibendum.txt"
type nul > "dapibus.txt"
type nul > "dolor.txt"
type nul > "sed.txt"
type nul > "lobortis.txt"
type nul > "justo.txt"
type nul > "Nunc.txt"
type nul > "elementum.txt"
type nul > "leo.txt"
type nul > "vel.txt"
type nul > "quam.txt"
type nul > "maximus.txt"
type nul > "elementum.txt"
type nul > "Nam.txt"
type nul > "non.txt"
type nul > "tellus.txt"
type nul > "non.txt"
type nul > "orci.txt"
type nul > "imperdiet.txt"
type nul > "luctus.txt"
type nul > "id.txt"
type nul > "at.txt"
type nul > "sapien.txt"
type nul > "Nulla.txt"
type nul > "lacinia.txt"
type nul > "tristique.txt"
type nul > "tortor.txt"
type nul > "sit.txt"
type nul > "amet.txt"
type nul > "mattis.txt"
type nul > "Cras.txt"
type nul > "tincidunt.txt"
type nul > "sem.txt"
type nul > "sed.txt"
type nul > "porttitor.txt"
type nul > "luctus.txt"
type nul > "mauris.txt"
type nul > "est.txt"
type nul > "venenatis.txt"
type nul > "elit.txt"
type nul > "sit.txt"
type nul > "amet.txt"
type nul > "lacinia.txt"
type nul > "arcu.txt"
type nul > "augue.txt"
type nul > "eget.txt"
type nul > "ligula.txt"
type nul > "Sed.txt"
type nul > "mauris.txt"
type nul > "justo.txt"
type nul > "feugiat.txt"
type nul > "id.txt"
type nul > "dolor.txt"
type nul > "mollis.txt"
type nul > "pharetra.txt"
type nul > "tristique.txt"
type nul > "ligula.txt"
type nul > "Quisque.txt"
type nul > "consequat.txt"
type nul > "dui.txt"
type nul > "luctus.txt"
type nul > "cursus.txt"
type nul > "dolor.txt"
type nul > "vitae.txt"
type nul > "ultrices.txt"
type nul > "orci.txt"
type nul > "Suspendisse.txt"
type nul > "imperdiet.txt"
type nul > "laoreet.txt"
type nul > "est.txt"
type nul > "feugiat.txt"
type nul > "ullamcorper.txt"
type nul > "purus.txt"
type nul > "dignissim.txt"
type nul > "ut.txt"
type nul > "Nulla.txt"
type nul > "et.txt"
type nul > "arcu.txt"
type nul > "sit.txt"
type nul > "amet.txt"
type nul > "nunc.txt"
type nul > "cursus.txt"
type nul > "feugiat.txt"
type nul > "Ut.txt"
type nul > "et.txt"
type nul > "mollis.txt"
type nul > "ligula.txt"
type nul > "Vestibulum.txt"
type nul > "ante.txt"
type nul > "ipsum.txt"
type nul > "primis.txt"
type nul > "in.txt"
type nul > "faucibus.txt"
type nul > "orci.txt"
type nul > "luctus.txt"
type nul > "et.txt"
type nul > "ultrices.txt"
type nul > "posuere.txt"
type nul > "cubilia.txt"
type nul > "curae.txt"
type nul > "Proin.txt"
type nul > "iaculis.txt"
type nul > "ornare.txt"
type nul > "tortor.txt"
type nul > "eu.txt"
type nul > "tincidunt.txt"
type nul > "nulla.txt"
type nul > "porttitor.txt"
type nul > "at.txt"
type nul > "Nam.txt"
type nul > "vehicula.txt"
type nul > "dolor.txt"
type nul > "at.txt"
type nul > "tincidunt.txt"
type nul > "commodo.txt"
type nul > "tortor.txt"
type nul > "ex.txt"
type nul > "gravida.txt"
type nul > "libero.txt"
type nul > "sit.txt"
type nul > "amet.txt"
type nul > "consectetur.txt"
type nul > "enim.txt"
type nul > "turpis.txt"
type nul > "non.txt"
type nul > "eros.txt"
type nul > "Nunc.txt"
type nul > "eu.txt"
type nul > "hendrerit.txt"
type nul > "justo.txt"
type nul > "Donec.txt"
type nul > "in.txt"
type nul > "neque.txt"
type nul > "pulvinar.txt"
type nul > "dictum.txt"
type nul > "lectus.txt"
type nul > "ut.txt"
type nul > "malesuada.txt"
type nul > "lacus.txt"
type nul > "Vivamus.txt"
type nul > "nec.txt"
type nul > "neque.txt"
type nul > "mi.txt"
type nul > "Mauris.txt"
type nul > "erat.txt"
type nul > "nulla.txt"
type nul > "rhoncus.txt"
type nul > "at.txt"
type nul > "tellus.txt"
type nul > "ut.txt"
type nul > "faucibus.txt"
type nul > "egestas.txt"
type nul > "nisl.txt"
type nul > "Donec.txt"
type nul > "ornare.txt"
type nul > "leo.txt"
type nul > "ac.txt"
type nul > "tempor.txt"
type nul > "condimentum.txt"
type nul > "Nunc.txt"
type nul > "malesuada.txt"
type nul > "tellus.txt"
type nul > "eget.txt"
type nul > "massa.txt"
type nul > "blandit.txt"
type nul > "volutpat.txt"
type nul > "Morbi.txt"
type nul > "laoreet.txt"
type nul > "imperdiet.txt"
type nul > "neque.txt"
type nul > "ac.txt"
type nul > "vulputate.txt"
type nul > "mauris.txt"
type nul > "commodo.txt"
type nul > "quis.txt"
type nul > "Maecenas.txt"
type nul > "vitae.txt"
type nul > "vulputate.txt"
type nul > "eros.txt"
type nul > "ut.txt"
type nul > "placerat.txt"
type nul > "lectus.txt"
type nul > "Fusce.txt"
type nul > "commodo.txt"
type nul > "leo.txt"
type nul > "neque.txt"
type nul > "ac.txt"
type nul > "sodales.txt"
type nul > "mauris.txt"
type nul > "gravida.txt"
type nul > "non.txt"
